<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>sel_api_archivos.Pruebas</RootNamespace>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="FluentAssertions" Version="8.10.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="NSubstitute" Version="5.3.0" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\sel-api-archivos.Api\sel-api-archivos.Api.csproj" />
    <ProjectReference Include="..\sel-api-archivos.Negocio\sel-api-archivos.Negocio.csproj" />
    <ProjectReference Include="..\sel-api-archivos.Datos\sel-api-archivos.Datos.csproj" />
    <ProjectReference Include="..\sel-api-archivos.Entidad\sel-api-archivos.Entidad.csproj" />
  </ItemGroup>

</Project>