<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\sel-api-archivos.Datos\sel-api-archivos.Datos.csproj" />
    <ProjectReference Include="..\sel-api-archivos.Entidad\sel-api-archivos.Entidad.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <RootNamespace>sel_api_archivos.Negocio</RootNamespace>
  </PropertyGroup>

</Project>
