<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.2.0" />
    <PackageReference Include="Microsoft.Extensions.Caching.Abstractions" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\sel-api-archivos.Datos\sel-api-archivos.Datos.csproj" />
    <ProjectReference Include="..\sel-api-archivos.Entidad\sel-api-archivos.Entidad.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <RootNamespace>sel_api_archivos.Negocio</RootNamespace>
  </PropertyGroup>

</Project>
