<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\sel-api-archivos.Negocio\sel-api-archivos.Negocio.csproj" />
    <ProjectReference Include="..\sel-api-archivos.Entidad\sel-api-archivos.Entidad.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.0" />
    <PackageReference Include="Serilog.AspNetCore" Version="8.0.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="5.0.1" />
    <PackageReference Include="Serilog.Formatting.Compact" Version="2.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.4.0" />
  </ItemGroup>

  <PropertyGroup>
    <RootNamespace>sel_api_archivos.Api</RootNamespace>
  </PropertyGroup>

</Project>
